name: flandresy
description: FlandreSY 2.0 Flutter rewrite.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/legacy/images/
  fonts:
    - family: FutureRoundSC
      fonts:
        - asset: assets/legacy/fonts/future_round_sc_regular.ttf
